/*
 * See the NOTICE file distributed with this work for additional
 * information regarding copyright ownership.
 *
 * This program is free software: you can redistribute it and/or modify
 * it under the terms of the GNU Affero General Public License as published by
 * the Free Software Foundation, either version 3 of the License, or
 * (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
 * GNU Affero General Public License for more details.
 *
 * You should have received a copy of the GNU Affero General Public License
 * along with this program.  If not, see http://www.gnu.org/licenses/
 */
package org.phenotips.termrequester.github;

import java.io.IOException;
import java.io.InputStream;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

import org.apache.http.client.fluent.Request;
import org.apache.http.entity.ContentType;

import org.junit.After;
import org.junit.Before;
import org.junit.BeforeClass;
import org.junit.Ignore;
import org.junit.Test;

import org.phenotips.termrequester.Phenotype;
import org.phenotips.termrequester.di.TermRequesterBackendModule;

import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.ObjectMapper;

import com.google.common.base.Optional;
import com.google.inject.Guice;
import com.google.inject.Injector;

import static org.junit.Assert.assertEquals;
import static org.junit.Assert.assertFalse;
import static org.junit.Assert.assertNotNull;
import static org.junit.Assert.assertTrue;
import static org.junit.Assert.fail;

import static org.mockito.Mockito.any;
import static org.mockito.Mockito.never;
import static org.mockito.Mockito.spy;
import static org.mockito.Mockito.verify;

/**
 * Tests the GithubAPIImpl class.
 *
 * @version $Id$
 */
public class GithubAPIImplTest
{
    /**
     * The github user whose repo we're gonna hit.
     */
    private static final String USER = "josecv";

    /**
     * The github repo to hit.
     */
    private static final String REPO = "Sandbox";

    /**
     * The OAuth Token we're using for auth.
     * TODO How can we fill this in when testing?
     * github revokes it when it makes its way into a commit (for obvious security reasons)
     */
    private static final String TEST_TOKEN = "";

    /**
     * The guice injector to use.
     */
    private static Injector injector;

    /**
     * An object mapper to deserialize from json.
     */
    private static ObjectMapper mapper;

    /**
     * The factory to build clients.
     */
    private static GithubAPIFactory factory;

    /**
     * The client under test.
     */
    private GithubAPI client;

    /**
     * A test phenotype.
     */
    private Phenotype pt;

    /**
     * The issues to cleanup at the end.
     */
    private List<String> cleanupIssues;

    /**
     * Set up the suite.
     */
    @BeforeClass
    public static void beforeClass()
    {
        injector = Guice.createInjector(new TermRequesterBackendModule());
        mapper = injector.getInstance(ObjectMapper.class);
        factory = injector.getInstance(GithubAPIFactoryImpl.class);
    }

    /**
     * Set up the test.
     */
    @Before
    public void setUp() throws IOException
    {
        client = factory.create(new GithubAPI.Repository(USER, REPO, TEST_TOKEN));
        pt = new Phenotype("unittest", "Issue autogenerated by unit test in org.phenotips.termrequester.github.GithubAPIImplTest");
        pt.setId("id");
        pt.addSynonym("one");
        pt.addSynonym("two");
        cleanupIssues = new ArrayList<>();
    }

    /**
     * Tear down the test, closing any issues we opened.
     */
    @After
    public void tearDown() throws IOException
    {
        for (String issue : cleanupIssues) {
            closeIssue(issue);
        }
    }

    /**
     * Close the issue with the number given.
     * @param number the number
     */
    private void closeIssue(String number) throws IOException
    {
        String endpoint = String.format("https://api.github.com/repos/%s/%s/issues/%s", USER, REPO, number);
        Map<String, String> params = new HashMap<>();
        params.put("state", "closed");
        params.put("title", "Unit testing auto-opened issue");
        byte[] bytes = mapper.writeValueAsBytes(params);
        Request.Patch(endpoint).bodyByteArray(bytes, ContentType.APPLICATION_JSON).
            addHeader("Authorization", "token " + TEST_TOKEN).
            execute().returnContent();
    }

    /**
     * Test that a new issue can be created for a simple phenotype.
     */
    @Test
    public void testOpenIssue() throws IOException, InterruptedException
    {
        String expectedDescription = pt.issueDescribe();
        client.openIssue(pt);
        Thread.sleep(1000);
        String number = pt.getIssueNumber().get();
        cleanupIssues.add(number);
        assertNotNull(number);
        String endpoint = String.format("https://api.github.com/repos/%s/%s/issues/%s", USER, REPO, number);
        InputStream is = Request.Get(endpoint).execute().returnContent().asStream();
        DataTypes.Issue issue = mapper.readValue(is, DataTypes.Issue.class);
        assertEquals(expectedDescription, issue.body);
        assertEquals("open", issue.state);
    }

    /**
     * Test the patch issue method.
     */
    @Test
    public void testPatchIssue() throws IOException, InterruptedException
    {
        client.openIssue(pt);
        String number = pt.getIssueNumber().get();
        cleanupIssues.add(number);
        pt.setName("different name!");
        String expectedDescription = pt.issueDescribe();
        String etag = pt.getEtag();
        client.patchIssue(pt);
        /* Gotta make sure the patched issue makes its way into the db */
        Thread.sleep(1000);
        String endpoint = String.format("https://api.github.com/repos/%s/%s/issues/%s", USER, REPO, number);
        InputStream is = Request.Get(endpoint).execute().returnContent().asStream();
        DataTypes.Issue issue = mapper.readValue(is, DataTypes.Issue.class);
        assertEquals(expectedDescription, issue.body);
        assertNotNull(etag, pt.getEtag());
    }

    /**
     * Test that the searchForIssue method works.
     */
    @Test
    public void testSearchForIssue() throws IOException, InterruptedException
    {
        assertFalse(client.searchForIssue(pt).isPresent());
        client.openIssue(pt);
        cleanupIssues.add(pt.getIssueNumber().get());
        Optional<String> number = client.searchForIssue(pt);
        assertTrue(number.isPresent());
        assertEquals(pt.getIssueNumber().get(), number.get());
        Phenotype pt2 = new Phenotype(pt.getName(), pt.getDescription());
        /* We need to allow time for the new issue to be indexed, otherwise if we request
         * it really quickly it won't come back.
         * This was a horrible thing to debug as you might guess */
        Thread.sleep(3000);
        number = client.searchForIssue(pt2);
        assertTrue(number.isPresent());
        assertEquals(pt.getIssueNumber().get(), number.get());
    }

    /**
     * Test we can't create an issue twice.
     */
    @Test
    public void testNoIssueRecreation() throws IOException
    {
        client.openIssue(pt);
        cleanupIssues.add(pt.getIssueNumber().get());
        try {
            client.openIssue(pt);
            fail("Did not fail on issue re-open");
        } catch (IllegalArgumentException e) {

        }
    }

    /**
     * Test that the status is properly updated.
     */
    @Test
    public void testStatus() throws IOException
    {
        client.openIssue(pt);
        assertEquals(Phenotype.Status.SUBMITTED, pt.getStatus());
        closeIssue(pt.getIssueNumber().get());
        client.readPhenotype(pt);
        assertEquals(Phenotype.Status.ACCEPTED, pt.getStatus());
    }

    /**
     * Test that we won't re-read the phenotype if it's not necessary.
     */
    @Test
    public void testNoReRead() throws IOException
    {
        client.openIssue(pt);
        cleanupIssues.add(pt.getIssueNumber().get());
        Phenotype ptSpy = spy(pt);
        client.readPhenotype(ptSpy);
        verify(ptSpy, never()).setStatus(any(Phenotype.Status.class));
        verify(ptSpy, never()).setEtag(any(String.class));
    }

    /**
     * Test that we won't re-write the phenotype if it's not necessary.
     * Marked as ignore because github doesn't actually return a 304 when we patch
     * without it being necessary. Ideally we need a concept of "github-dirty".
     */
    @Test
    @Ignore
    public void testNoReWrite() throws IOException
    {
        client.openIssue(pt);
        cleanupIssues.add(pt.getIssueNumber().get());
        Phenotype ptSpy = spy(pt);
        client.patchIssue(ptSpy);
        verify(ptSpy, never()).setEtag(any(String.class));
    }
}
